SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
                        FROM REST_INFO
                        GROUP BY FOOD_TYPE)AS B JOIN REST_INFO AS A 
USING (FOOD_TYPE, FAVORITES)
ORDER BY FOOD_TYPE DESC