SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I LEFT JOIN ANIMAL_OUTS O
                  ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.SEX_UPON_INTAKE LIKE 'Intact%'
    AND I.ANIMAL_ID IN (SELECT ANIMAL_ID FROM ANIMAL_OUTS 
                        WHERE SEX_UPON_OUTCOME LIKE 'Neutered%'
                       OR SEX_UPON_OUTCOME LIKE 'Spayed%' )