-- 코드를 입력하세요
SELECT WAREHOUSE_ID,WAREHOUSE_NAME,ADDRESS,IFNULL(FREEZER_YN,'N') AS FREEZER_YN 
FROM FOOD_WAREHOUSE 
WHERE WAREHOUSE_NAME LIKE '%경기%'  # 'WAREHOUSE_NAME' %%: 컬럼에 '경기'라는 글자가 어느 위치든 포함이 되어있다면 ~
ORDER BY WAREHOUSE_ID
