-- 코드를 입력하세요
# 정답 코드
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    AND PRICE IN (SELECT MAX(PRICE) FROM FOOD_PRODUCT 
                  GROUP BY CATEGORY)
ORDER BY PRICE DESC

-- ORDER BY에는 집계함수X

# 오답 코드
# SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE, PRODUCT_NAME
# FROM FOOD_PRODUCT
# WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
# GROUP BY CATEGORY
# ORDER BY PRICE DESC
